CREATE TABLE `products` (
  `P_CODE` int(11) NOT NULL AUTO_INCREMENT,
  `P_DESCRIPTION` varchar(250) DEFAULT NULL,
  `P_PRICE` int(11) DEFAULT NULL,
  `P_QUANTITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`P_CODE`)
)