CREATE TABLE `customers` (
  `C_CODE` varchar(100) NOT NULL,
  `C_NAME` varchar(100) DEFAULT NULL,
  `C_ADDRESS` varchar(225) DEFAULT NULL,
  `C_PHONE1` varchar(45) DEFAULT NULL,
  `C_PHONE2` varchar(45) DEFAULT NULL,
  `C_CREDITLIMIT` varchar(100) DEFAULT NULL,
  `C_CURRENTLIMIT` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`C_CODE`)
);