CREATE TABLE `products` (
  `P_CODE` varchar(100) NOT NULL,
  `P_DESCRIPTION` varchar(250) DEFAULT NULL,
  `P_PRICE` varchar(100) DEFAULT NULL,
  `P_QUANTITY` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`P_CODE`)
);