CREATE TABLE `LINE_ITEMS` (
  `LI_CODE` int(11) NOT NULL AUTO_INCREMENT,
  `LI_QUANTITY` varchar(100) NOT NULL,
  `LI_ORDER_NO` varchar(100) NOT NULL,
  `LI_PRODUCT_ID` varchar(100) NOT NULL,
  PRIMARY KEY (`LI_CODE`)
);