CREATE TABLE `LINE_ITEMS` (
  `LI_CODE` int(11) NOT NULL AUTO_INCREMENT,
  `LI_QUANTITY` varchar(45) NOT NULL,
  `LI_ORDER_NO` int(11) NOT NULL,
  `LI_PRODUCT_ID` int(11) NOT NULL,
  PRIMARY KEY (`LI_CODE`)
);