CREATE TABLE `LINE_ITEMS` (
  `LI_CODE` varchar(100) NOT NULL,
  `LI_QUANTITY` varchar(100) NOT NULL,
  `LI_ORDER_NO` varchar(100) NOT NULL,
  `LI_PRODUCT_ID` varchar(100) NOT NULL,
  PRIMARY KEY (`LI_CODE`)
);