ALTER TABLE LINE_ITEMS
ADD CONSTRAINT fk_lineItems_product
FOREIGN KEY (LI_PRODUCT_ID)
REFERENCES PRODUCTS(P_CODE);


ALTER TABLE LINE_ITEMS
ADD CONSTRAINT fk_lineItems_saleOrders
FOREIGN KEY (LI_ORDER_NO)
REFERENCES SALE_ORDERS(LI_ORDER_NO);